/// Flutter icons AEIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  AEIcons
///      fonts:
///       - asset: fonts/AEIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class AEIcons {
  AEIcons._();

  static const _kFontFam = 'AEIcons';
  static const String? _kFontPkg = null;

  static const IconData checked = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData client = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dashboard = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData date = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData distribution = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData export_icon = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData filter = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData more = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData next = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData next_page = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData order = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData print = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData product = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData promo = IconData(0xe80d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData report = IconData(0xe80e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData seach = IconData(0xe80f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData settings = IconData(0xe810, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData status = IconData(0xe811, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData store = IconData(0xe812, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData support = IconData(0xe813, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
